vich_uploader:
    db_driver: orm

    mappings:
        exercisesFiles:
            uri_prefix: /exercises_files
            upload_destination: '%kernel.project_dir%/public/exercises_files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profilePictures:
            uri_prefix: /profile_pictures
            upload_destination: '%kernel.project_dir%/public/profile_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

